# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements_dev.txt
script:
    - flake8
    - coverage run --source scumdoc_parser setup.py test
after_success:
    - coveralls



